services:
  linkradar:
    build: .
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads

  ui:
    build: .
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
    entrypoint: ["python", "app.py"]
    ports:
      - "7860:7860"
